const test = require('node:test');
const assert = require('node:assert/strict');
const { request, resetDatabase, startTestEnvironment, stopTestEnvironment, getBaseUrl } = require('./helpers');
const { createAdmin, createCustomer, createProduct, setSettings, validAddress } = require('./factories');
const { createMasterOwner, createProvisionedSeller } = require('./accessFixtures');
const Product = require('../models/Product');
const VariantGroup = require('../models/VariantGroup');
const Store = require('../models/Store');
const Subscriber = require('../models/Subscriber');
const { readConfiguration } = require('../services/masterConfigurationService');
test.before(startTestEnvironment);
test.after(stopTestEnvironment);
test.beforeEach(async () => { await resetDatabase(); await setSettings(); });
async function call(method, route, body, token, status = 200, headers) {
  const result = await request(route, { method, body, token, headers });
  assert.equal(result.status, status, `${method} ${route}: ${JSON.stringify(result.data)}`);
  return result.data;
}
const get = (route, token, headers) => call('GET', route, undefined, token, 200, headers);

test('category create/read/update/hide/delete survives duplicate names and malformed IDs', async () => {
  const { token } = await createAdmin();
  const category = await call('POST', '/api/admin/categories', { name: 'Workflow Sarees', slug: 'workflow-sarees', image: '/uploads/category.jpg' }, token, 201);
  assert.equal((await get(`/api/admin/categories/${category._id}`, token)).name, 'Workflow Sarees');
  await call('POST', '/api/admin/categories', { name: 'Workflow Sarees', slug: category.slug }, token, 400);
  await call('GET', '/api/admin/categories/bad-id', undefined, token, 400);
  await call('PUT', `/api/admin/categories/${category._id}`, { name: '   ' }, token, 400);
  await call('PUT', `/api/admin/categories/${category._id}`, { name: 'Hidden Sarees', isActive: false }, token);
  assert.equal((await get('/api/admin/categories', token)).length, 1);
  assert.equal((await get('/api/categories?admin=true')).length, 0);
  await call('PUT', `/api/admin/categories/${category._id}`, { isActive: true }, token);
  assert.equal((await get('/api/categories')).length, 1);
  await call('DELETE', `/api/admin/categories/${category._id}`, undefined, token);
  assert.equal((await get('/api/admin/categories', token)).length, 0);
  await call('GET', `/api/admin/categories/${category._id}`, undefined, token, 404);
});

test('banner creation, visibility-only editing, reactivation and deletion retain campaign content', async () => {
  const { token } = await createAdmin();
  const banner = await call('POST', '/api/admin/banners', { title: 'Festive Edit', subtitle: 'Celebration styles', buttonText: 'Shop now', link: '/products', image: '/uploads/banner.jpg', isActive: true }, token, 201);
  const hidden = await call('PUT', `/api/admin/banners/${banner._id}`, { isActive: false }, token);
  assert.equal(hidden.subtitle, banner.subtitle); assert.equal(hidden.buttonText, banner.buttonText); assert.equal(hidden.link, banner.link);
  assert.equal((await get('/api/admin/banners', token)).length, 1);
  assert.equal((await get('/api/banners?admin=true')).length, 0);
  await call('PUT', `/api/admin/banners/${banner._id}`, { isActive: true }, token);
  assert.equal((await get(`/api/admin/banners/${banner._id}`, token)).title, 'Festive Edit');
  assert.equal((await get('/api/banners')).length, 1);
  await call('GET', '/api/admin/banners/not-an-id', undefined, token, 400);
  await call('DELETE', `/api/admin/banners/${banner._id}`, undefined, token);
  await call('DELETE', `/api/admin/banners/${banner._id}`, undefined, token, 404);
});

test('variant-group CRUD preserves membership on metadata edits and safely transfers products between groups', async () => {
  const { token } = await createAdmin();
  const first = await createProduct(), second = await createProduct(), hidden = await createProduct({ isActive: false });
  const groupA = (await call('POST', '/api/admin/variant-groups', { name: 'Color Family', productIds: [String(first._id), String(second._id), String(hidden._id)], colors: ['Rose','Wine'], sizes: ['M','L'] }, token, 201)).data;
  const renamed = (await call('PUT', `/api/admin/variant-groups/${groupA._id}`, { name: 'Premium Color Family' }, token)).data;
  assert.equal(renamed.products.length, 3); assert.deepEqual(renamed.colors, ['Rose','Wine']);
  assert.equal((await get(`/api/variant-groups/${groupA._id}`)).data.products.length, 2);
  const groupB = (await call('POST', '/api/admin/variant-groups', { name: 'Second Family', productIds: [String(second._id)] }, token, 201)).data;
  assert.equal((await VariantGroup.findById(groupA._id)).products.some(id => String(id) === String(second._id)), false);
  await call('POST', `/api/admin/variant-groups/${groupA._id}/remove-products`, { productIds: [String(second._id)] }, token);
  assert.equal(String((await Product.findById(second._id)).variantGroupId), String(groupB._id));
  await call('POST', `/api/admin/variant-groups/${groupB._id}/add-products`, { productIds: [String(first._id)] }, token);
  await call('POST', `/api/admin/variant-groups/${groupB._id}/remove-products`, { productIds: [String(first._id)] }, token);
  assert.equal((await Product.findById(first._id)).variantGroupId, undefined);
  await call('PUT', `/api/admin/variant-groups/${groupB._id}`, { isActive: false }, token);
  await call('GET', `/api/variant-groups/${groupB._id}`, undefined, undefined, 404);
  assert.equal((await get('/api/admin/variant-groups', token)).data.length, 2);
  assert.equal((await get('/api/variant-groups')).data.length, 1);
  await call('POST', '/api/admin/variant-groups', { name: 'Invalid', productIds: ['0123456789abcdef99999999'] }, token, 400);
  assert.equal(await VariantGroup.countDocuments({ name: 'Invalid' }), 0);
  await call('DELETE', `/api/admin/variant-groups/${groupA._id}`, undefined, token);
  await call('DELETE', `/api/admin/variant-groups/${groupB._id}`, undefined, token);
  assert.equal((await Product.findById(second._id)).variantGroupId, undefined);
});

test('customer journey logs in, edits addresses, purchases, follows fulfilment, reviews and returns the item', async () => {
  const customer = await createCustomer({ phone: '9123456789' });
  const admin = await createAdmin(); const product = await createProduct({ stock: 7 });
  await call('POST', '/api/auth/send-otp', { phone: customer.user.phone });
  const login = await call('POST', '/api/auth/verify-otp', { phone: customer.user.phone, otp: '123456' });
  const token = login.token;
  assert.equal((await get('/api/auth/me', token)).phone, customer.user.phone);
  const refreshed = await call('POST', '/api/auth/refresh', { refreshToken: login.refreshToken });
  assert.ok(refreshed.token);
  let addresses = await call('POST', '/api/user/addresses', validAddress({ mobile: customer.user.phone }), token, 201);
  const firstAddressId = addresses[0]._id;
  addresses = await call('POST', '/api/user/addresses', validAddress({ mobile: customer.user.phone, addressType: 'Work', houseNo: 'Office 4' }), token, 201);
  const secondAddressId = addresses[1]._id;
  await call('PATCH', `/api/user/addresses/${secondAddressId}/default`, {}, token);
  await call('PUT', `/api/user/addresses/${secondAddressId}`, { ...addresses[1], houseNo: 'Office 8', isDefault: true }, token);
  await call('DELETE', `/api/user/addresses/${firstAddressId}`, undefined, token);
  addresses = await get('/api/user/addresses', token); assert.equal(addresses[0].houseNo, 'Office 8'); assert.equal(addresses[0].isDefault, true);
  await call('POST', `/api/wishlist/${product._id}`, {}, token);
  assert.equal((await get('/api/wishlist', token)).length, 1);
  const bag = await call('POST', '/api/cart', { product: String(product._id), size: 'M', color: 'Red', quantity: 1 }, token, 201);
  await call('POST', '/api/cart/selection', { itemIds: [bag.items[0]._id], selected: false }, token);
  assert.equal((await get('/api/cart', token)).items[0].selected, false);
  await call('POST', '/api/cart/selection', { itemIds: [bag.items[0]._id], selected: true }, token);
  assert.equal((await call('POST', '/api/wishlist/resolve', { ids: [String(product._id)] }))[0]._id, String(product._id));
  await call('PUT', `/api/cart/${bag.items[0]._id}`, { quantity: 2 }, token);
  const quote = await call('POST', '/api/orders/quote', { orderItems: [{ product: String(product._id), quantity: 2, size: 'M', color: 'Red' }], shippingAddress: addresses[0], paymentMethod: 'COD' }, token);
  const order = await call('POST', '/api/orders', { orderItems: [{ product: String(product._id), quantity: 2, size: 'M', color: 'Red' }], shippingAddress: addresses[0], paymentMethod: 'COD' }, token, 201);
  assert.equal(order.finalAmount, quote.totals.finalAmount);
  await call('POST', '/api/cart/remove-items', { itemIds: [bag.items[0]._id] }, token);
  await call('DELETE', `/api/wishlist/${product._id}`, undefined, token);
  for (const orderStatus of ['Confirmed','Packed','Shipped','Out for Delivery','Delivered']) await call('PUT', `/api/admin/orders/${order._id}/status`, { orderStatus }, admin.token);
  const detail = await get(`/api/orders/${order._id}`, token); assert.equal(detail.orderStatus, 'Delivered');
  assert.equal((await get('/api/orders/my-orders', token)).length, 1);
  assert.equal((await get(`/api/orders/${order._id}/receipt`, token)).finalAmount, order.finalAmount);
  const review = await call('POST', `/api/reviews/${product._id}`, { rating: 5, title: 'Lovely', comment: 'Good quality and the size fits well.' }, token, 201);
  assert.equal((await get(`/api/reviews/${product._id}/mine`, token)).rating, 5);
  await call('PUT', `/api/reviews/${review._id}`, { rating: 4, title: 'Great', comment: 'Updated review after wearing the product.' }, token);
  assert.equal((await get('/api/reviews/featured')).length, 1);
  assert.equal((await get('/api/admin/reviews', admin.token)).length, 1);
  await call('PATCH', `/api/admin/reviews/${review._id}/visibility`, { isVisible: false }, admin.token);
  assert.equal((await get('/api/reviews/featured')).length, 0);
  await call('PATCH', `/api/admin/reviews/${review._id}/visibility`, { isVisible: true }, admin.token);
  await call('DELETE', `/api/admin/reviews/${review._id}`, undefined, admin.token);
  assert.equal((await Product.findById(product._id)).numReviews, 0);
  const returns = await call('POST', '/api/returns', { order: order._id, product: String(product._id), orderItemId: order.orderItems[0]._id, quantity: 1, type: 'return', reason: 'Size issue' }, token, 201);
  assert.equal((await get('/api/admin/returns', admin.token)).length, 1);
  assert.equal((await get(`/api/returns/order/${order._id}`, token)).requests.length, 1);
  for (const status of ['Approved','Pickup Scheduled','Received','Refunded','Closed']) await call('PUT', `/api/admin/returns/${returns._id}/status`, { status }, admin.token);
  assert.equal((await Product.findById(product._id)).stock, 6);
  assert.equal((await get('/api/returns/my-requests', token)).length, 1);
  const notifications = await get('/api/notifications', token); assert.ok(notifications.length > 0);
  await call('PATCH', `/api/notifications/${notifications[0]._id}/read`, { read: true }, token);
  await call('PATCH', `/api/notifications/${notifications[0]._id}/read`, { read: false }, token);
  await call('PATCH', '/api/notifications/read-all', {}, token);
  assert.equal((await get('/api/notifications/summary', token)).unreadCount, 0);
  const replacement = await call('POST', '/api/cart', { product: String(product._id), size: 'M', color: 'Red', quantity: 1 }, token, 201);
  await call('DELETE', `/api/cart/${replacement.items[0]._id}`, undefined, token);
  await call('DELETE', '/api/cart', undefined, token);
  assert.equal((await get('/api/cart', token)).items.length, 0);
  await call('POST', '/api/auth/logout', {}, token);
});

test('support and newsletter actions persist and the seller inbox closes a conversation without external delivery', async () => {
  const seller = await createProvisionedSeller('Workflow Boutique');
  await Store.updateOne({ _id: seller.store.id }, { status: 'PUBLISHED' });
  const headers = { 'x-store-id': seller.store.id };
  const customer = await createCustomer(); const admin = await createAdmin();
  const created = await call('POST', `/api/contact?store=${seller.store.slug}`, { name: 'Workflow Customer', email: customer.user.email, phone: customer.user.phone, subject: 'Sizing help', message: 'Please help me choose the correct product size.' }, customer.token, 201);
  const inbox = await get('/api/seller/inbox', seller.token, headers); assert.equal(inbox.length, 1);
  const opened = await get(`/api/seller/inbox/${inbox[0]._id}`, seller.token, headers); assert.equal(opened.messages.length, 1);
  await call('POST', `/api/seller/inbox/${inbox[0]._id}/reply`, { body: 'This is a stored fixture reply only.', status: 'PENDING' }, seller.token, 201, headers);
  await call('PUT', `/api/seller/inbox/${inbox[0]._id}/status`, { status: 'RESOLVED' }, seller.token, 200, headers);
  assert.equal((await get(`/api/seller/inbox/${inbox[0]._id}`, seller.token, headers)).messages.length, 2);
  await call('PUT', `/api/admin/contact/${created.id}/status`, { status: 'CLOSED', adminNote: 'Handled in fixture inbox' }, admin.token);
  assert.equal((await get('/api/admin/contact?status=CLOSED', admin.token)).length, 1);
  await call('POST', '/api/newsletter/subscribe', { email: ' workflow@isolated.test ' }, undefined, 201);
  await call('POST', '/api/newsletter/unsubscribe', { email: 'workflow@isolated.test' });
  assert.equal((await Subscriber.findOne({ email: 'workflow@isolated.test' })).isActive, false);
  await call('POST', '/api/newsletter/subscribe', { email: 'workflow@isolated.test' });
  assert.equal((await Subscriber.findOne({ email: 'workflow@isolated.test' })).isActive, true);
  assert.equal((await get('/api/admin/newsletter', admin.token)).length, 1);
});

test('master configuration round-trips a template, custom preset and locked state through guarded APIs', async () => {
  const master = await createMasterOwner(); const admin = await createAdmin();
  const workspace = await get('/api/master', master.token);
  const configuration = workspace.configuration.locked
    ? await call('PUT', '/api/master/configuration', { revision: workspace.configuration.revision, locked: false }, master.token)
    : workspace.configuration;
  const exported = await get('/api/master/export', master.token);
  assert.equal(exported.format, 'samira-store-template');
  const preset = await call('POST', '/api/master/presets', { name: 'Workflow Template', structure: exported.structure }, master.token, 201);
  const imported = await call('POST', '/api/master/import', { template: exported, revision: configuration.revision }, master.token);
  const locked = await call('PUT', '/api/master/configuration', { revision: imported.revision, locked: true }, master.token);
  assert.equal(locked.locked, true);
  await call('POST', '/api/master/import', { template: exported, revision: locked.revision }, master.token, 403);
  await call('PUT', '/api/master/configuration', { revision: locked.revision, locked: false }, master.token);
  await call('DELETE', `/api/master/presets/${preset._id}`, undefined, master.token);
  await call('GET', '/api/master', undefined, admin.token, 403);
  const settings = await get('/api/admin/settings', master.token);
  await call('PUT', '/api/admin/settings', { ...settings, storeName: 'Workflow Collection', deliveryCharge: 55 }, master.token);
  assert.equal((await get('/api/settings')).deliveryCharge, 55);
  assert.ok((await get('/api/catalog-configuration')).industry);
  assert.equal((await readConfiguration()).locked, false);
});

test('profile phone and email OTP verification persists edits, rejects reused identities and allows account deletion', async () => {
  const customer = await createCustomer();
  const token = customer.token;
  const nextPhone = '9123456790', nextEmail = 'updated@workflow.test';
  await call('POST', '/api/auth/profile/send-phone-change-otp', { phone: nextPhone }, token);
  const phone = await call('POST', '/api/auth/profile/verify-phone-change-otp', { phone: nextPhone, otp: '123456' }, token);
  const emailSent = await call('POST', '/api/auth/profile/send-email-change-otp', { email: nextEmail }, token);
  const email = await call('POST', '/api/auth/profile/verify-email-change-otp', { email: nextEmail, otp: emailSent.demoOtp || emailSent.devOtp }, token);
  const updated = await call('PUT', '/api/auth/profile', { name: 'Updated Customer', phone: nextPhone, email: nextEmail, phoneVerificationToken: phone.verificationToken, emailVerificationToken: email.verificationToken, alternatePhone: '9123456789', gender: 'female', birthDate: '1995-03-14', hintName: 'Near park' }, token);
  assert.equal(updated.phone, nextPhone); assert.equal(updated.email, nextEmail); assert.equal(updated.isEmailVerified, true);
  assert.equal((await get('/api/auth/profile', token)).alternatePhone, '9123456789');
  const stranger = await createCustomer();
  await call('POST', '/api/auth/profile/send-phone-change-otp', { phone: nextPhone }, stranger.token, 400);
  await call('POST', '/api/auth/profile/send-email-change-otp', { email: nextEmail }, stranger.token, 400);
  await call('DELETE', '/api/auth/profile', undefined, token);
  await call('GET', '/api/auth/me', undefined, token, 401);
});

test('seller CRM, campaign analytics, manual shipment and reports agree with its purchased order', async () => {
  const seller = await createProvisionedSeller('Commerce Workflow');
  await Store.updateOne({ _id: seller.store.id }, { status: 'PUBLISHED' });
  const headers = { 'x-store-id': seller.store.id };
  const customer = await createCustomer();
  const product = await createProduct({ storeId: seller.store.id, stock: 8 });
  assert.equal((await get('/api/stores', seller.token)).length, 1);
  assert.ok(await get('/api/stores/me/current', seller.token, headers));
  assert.equal((await get(`/api/stores/${seller.store.slug}`)).slug, seller.store.slug);
  assert.ok(await get('/api/seller/audit-logs/options', seller.token, headers));
  assert.equal((await get('/api/seller/instagram', seller.token, headers)).status, 'DISCONNECTED');
  assert.equal((await call('POST', '/api/seller/instagram', { username: 'fixture-boutique' }, seller.token, 200, headers)).status, 'DISCONNECTED');
  const callback = await fetch(`${getBaseUrl()}/api/instagram/oauth/callback`, { redirect: 'manual' });
  assert.equal(callback.status, 302);
  assert.match(callback.headers.get('location'), /\/seller\/instagram\?ig=error$/);
  for (const name of ['STORE_VIEW','PRODUCT_VIEW','ADD_TO_CART','BEGIN_CHECKOUT']) await call('POST', `/api/analytics/events?store=${seller.store.slug}`, { name, productId: String(product._id), sessionId: 'workflow-analytics-session', source: 'instagram', campaign: 'workflow-launch' }, customer.token, 202);
  const order = await call('POST', '/api/orders/cod', { orderItems: [{ product: String(product._id), quantity: 1, size: 'M', color: 'Red' }], shippingAddress: validAddress(), paymentMethod: 'COD', attribution: { source: 'instagram', campaign: 'workflow-launch' } }, customer.token, 201);
  assert.equal((await get('/api/seller/orders', seller.token, headers)).length, 1);
  assert.equal((await get(`/api/seller/orders/${order._id}`, seller.token, headers))._id, order._id);
  const shipment = await call('PUT', `/api/seller/orders/${order._id}/shipment`, { courierName: 'Fixture Courier', trackingNumber: 'FIXTURE-001', trackingUrl: 'https://example.test/tracking/FIXTURE-001', status: 'SHIPPED' }, seller.token, 200, headers);
  assert.equal(shipment.trackingNumber, 'FIXTURE-001');
  const updated = await call('PUT', `/api/seller/crm/${customer.user._id}`, { tags: ['VIP'], notes: 'Fixture customer sizing preference', acquisition: 'Instagram' }, seller.token, 200, headers);
  assert.deepEqual(updated.tags, ['VIP']);
  const crm = await get('/api/seller/crm', seller.token, headers); assert.equal(crm.length, 1); assert.equal(crm[0].notes, updated.notes);
  const funnel = await get('/api/seller/analytics/funnel?range=30d', seller.token, headers);
  assert.equal(funnel.events.PRODUCT_VIEW, 1); assert.equal(funnel.attributedSales[0].revenue, order.finalAmount);
  const sales = await get('/api/seller/reports/sales?range=30d', seller.token, headers); assert.equal(sales.totals.orders, 1);
  const productReport = await get('/api/seller/reports/products?range=30d', seller.token, headers); assert.equal(productReport.bestSellers[0].sold, 1);
  assert.ok(await get('/api/seller/dashboard/stats', seller.token, headers));
  const other = await createProvisionedSeller('Unrelated Workflow');
  await call('GET', `/api/seller/orders/${order._id}`, undefined, other.token, 404, { 'x-store-id': other.store.id });
  await call('PUT', `/api/seller/orders/${order._id}/status`, { orderStatus: 'Delivered' }, seller.token, 200, headers);
  const returnRequest = await call('POST','/api/returns',{order:order._id,product:String(product._id),quantity:1,type:'return',reason:'Fixture return'},customer.token,201);
  assert.equal((await get('/api/seller/returns',seller.token,headers)).length,1);
  await call('PUT',`/api/seller/returns/${returnRequest._id}/status`,{status:'Received'},other.token,404,{'x-store-id':other.store.id});
  assert.equal((await Product.findById(product._id)).stock,7);
  await call('PUT',`/api/seller/returns/${returnRequest._id}/status`,{status:'Received'},seller.token,200,headers);
  assert.equal((await Product.findById(product._id)).stock,8);
});

test('storefront catalog scope honors query and header navigation and never exposes hidden products', async () => {
  const main = await createProduct({ name: 'Main Workflow Saree' });
  const hidden = await createProduct({ name: 'Hidden Workflow Saree', isActive: false });
  const seller = await createProvisionedSeller('Scoped Workflow');
  const unpublished = await createProvisionedSeller('Not Published Workflow');
  await Store.updateOne({ _id: seller.store.id }, { status: 'PUBLISHED' });
  const sellerProduct = await createProduct({ storeId: seller.store.id, name: 'Scoped Workflow Saree' });
  const queryResult = await get(`/api/products?store=${seller.store.slug}`);
  const headerResult = await get('/api/products', undefined, { 'x-store-slug': seller.store.slug });
  assert.deepEqual(queryResult.map(p => p._id), [String(sellerProduct._id)]);
  assert.deepEqual(headerResult.map(p => p._id), [String(sellerProduct._id)]);
  assert.equal((await get('/api/products?admin=true')).some(p => p._id === String(hidden._id)), false);
  assert.equal((await get('/api/products?search=%5B')).length, 0);
  await call('GET', `/api/products/${hidden.slug}`, undefined, undefined, 404);
  await call('GET', `/api/products/${main.slug}?store=${seller.store.slug}`, undefined, undefined, 404);
  for (const endpoint of ['products','categories','banners']) {
    await call('GET', `/api/${endpoint}?store=${unpublished.store.slug}`, undefined, undefined, 404);
    await call('GET', `/api/${endpoint}`, undefined, undefined, 404, { 'x-store-slug': 'missing-workflow-store' });
  }
});

test('admin catalog editing, inventory actions, coupon lifecycle and dashboard all use persisted records', async () => {
  const admin = await createAdmin(); const customer = await createCustomer();
  const category = await call('POST', '/api/admin/categories', { name: 'Sarees', slug: 'workflow-sarees' }, admin.token, 201);
  const product = await call('POST', '/api/admin/products', { name: 'Workflow Silk Saree', sku: 'WORKFLOW-CRUD-1', category: category._id, price: 1000, originalPrice: 1600, stock: 5, images: [{ url: '/uploads/test.jpg', primary: true }], colors: ['Rose'], sizingMode: 'auto' }, admin.token, 201);
  const saved = await call('PUT', `/api/admin/products/${product._id}`, { ...product, name: 'Edited Workflow Silk Saree', description: 'Updated catalog details.' }, admin.token);
  assert.equal(saved.name, 'Edited Workflow Silk Saree');
  assert.equal((await get(`/api/admin/products/${product._id}`, admin.token)).description, 'Updated catalog details.');
  await call('PATCH', `/api/admin/products/${product._id}/stock`, { stock: 3 }, admin.token);
  assert.equal((await get('/api/admin/inventory/low-stock', admin.token)).length, 1);
  await call('PATCH', `/api/admin/products/${product._id}/mark-out-of-stock`, {}, admin.token);
  assert.equal((await get(`/api/products/${saved.slug}`)).stock, 0);
  await call('PATCH', `/api/admin/products/${product._id}/stock`, { stock: 5 }, admin.token);
  await call('PATCH', `/api/admin/products/${product._id}/hide`, {}, admin.token);
  await call('GET', `/api/products/${saved.slug}`, undefined, undefined, 404);
  await call('PATCH', `/api/admin/products/${product._id}/status`, { isActive: true }, admin.token);
  const coupon = await call('POST', '/api/admin/coupons', { code: 'WORKFLOW50', type: 'Flat', discountValue: 50, minOrderAmount: 500, expiryDate: new Date(Date.now()+86400000).toISOString(), isActive: true, isPublic: true }, admin.token, 201);
  const updated = await call('PUT', `/api/admin/coupons/${coupon._id}`, { ...coupon, discountValue: 75 }, admin.token);
  assert.equal(updated.discountValue, 75);
  assert.equal((await get('/api/admin/coupons', admin.token)).length, 1);
  assert.equal((await call('POST', '/api/coupons/available', { cartTotal: 1000, paymentMethod: 'COD' }, customer.token)).bestCouponCode, coupon.code);
  assert.equal((await call('POST', '/api/coupons/apply', { code: coupon.code, cartTotal: 1000, paymentMethod: 'COD' }, customer.token)).discountAmount, 75);
  const order = await call('POST', '/api/orders/cod', { orderItems: [{ product: product._id, quantity: 1, color: 'Rose' }], coupon: { code: coupon.code }, shippingAddress: validAddress(), paymentMethod: 'COD' }, customer.token, 201);
  assert.equal(order.couponDiscount, 75);
  await call('PUT', `/api/admin/orders/${order._id}/payment-status`, { paymentStatus: 'Paid' }, admin.token);
  const stats = await get('/api/admin/dashboard/stats', admin.token); assert.equal(stats.orders, 1); assert.equal(stats.revenue, order.finalAmount);
  assert.ok(await get('/api/admin/dashboard/overview', admin.token));
  assert.equal((await get('/api/admin/dashboard/recent-orders', admin.token)).length, 1);
  assert.equal((await call('DELETE', `/api/admin/coupons/${coupon._id}`, undefined, admin.token)).archived, true);
  assert.equal((await get('/api/coupons')).length, 0);
  await call('DELETE', `/api/admin/products/${product._id}`, undefined, admin.token);
  assert.equal((await Product.findById(product._id)).isArchived, true);
  assert.equal((await get(`/api/orders/${order._id}`, customer.token)).orderItems[0].name, saved.name);
  await call('DELETE', '/api/admin/products/malformed-id', undefined, admin.token, 400);
});

test('store content edits update published wording and reject stale saves without changing layout', async () => {
  const master = await createMasterOwner();
  await get('/api/admin/customization', master.token);
  const current = await get('/api/admin/store-content', master.token);
  assert.equal(current.available, true);
  const before = await get('/api/website-config');
  const saved = await call('PUT', '/api/admin/store-content', { revision: current.revision, content: { ...current.content, websiteName: 'Workflow Collection' }, sections: current.sections }, master.token);
  assert.ok(saved.revision);
  const published = await get('/api/website-config');
  assert.equal(published.config.branding.websiteName, 'Workflow Collection');
  assert.deepEqual(published.config.colors, before.config.colors);
  await call('PUT', '/api/admin/store-content', { revision: current.revision, content: current.content, sections: current.sections }, master.token, 409);
});

test('owner-controlled client admin handover and role switching retain guarded permissions', async (t) => {
  const master = await createMasterOwner(); const customer = await createCustomer();
  const keys = ['NODE_ENV','OTP_MODE','OTP_PROVIDER','SMS_PROVIDER'];
  const previous = Object.fromEntries(keys.map(key => [key,process.env[key]]));
  t.after(() => keys.forEach(key => { if(previous[key]===undefined) delete process.env[key]; else process.env[key]=previous[key]; }));
  Object.assign(process.env,{NODE_ENV:'production',OTP_MODE:'production',OTP_PROVIDER:'sms',SMS_PROVIDER:'twilio'});
  const provisioned = await call('POST','/api/master/client-admins',{name:'Provisioned Fixture Admin',phone:'9123456791'},master.token,201);
  assert.equal(provisioned.role,'admin'); assert.equal(provisioned.systemRole,'USER');
  const promoted = await call('PATCH',`/api/admin/customers/${customer.user._id}/promote-admin`,{},master.token);
  assert.equal(promoted.role,'admin');
  await call('PATCH',`/api/admin/customers/${customer.user._id}/demote-admin`,{},master.token);
  await call('PATCH',`/api/admin/customers/${customer.user._id}/block`,{isBlocked:true},master.token);
  await call('GET','/api/auth/me',undefined,customer.token,401);
  await call('PATCH',`/api/admin/customers/${customer.user._id}/block`,{isBlocked:false},master.token);
  assert.ok((await get('/api/admin/customers',master.token)).some(user=>String(user._id)===String(customer.user._id)));
  assert.ok((await get('/api/admin/audit-logs/options',master.token)).actions.length > 0);
  const admin = await createAdmin();
  let mode = await call('POST','/api/auth/switch-mode',{mode:'customer'},admin.token);
  assert.equal(mode.user.activeMode,'customer');
  mode = await call('POST','/api/auth/switch-mode',{mode:'admin'},mode.token);
  assert.equal(mode.user.activeMode,'admin');
  assert.ok(await get('/api/admin/profile',mode.token));
});

test('theme listing, draft discard and activation complete without publishing discarded content', async () => {
  const master = await createMasterOwner();
  const config = await readConfiguration();
  if(config.locked) await call('PUT','/api/master/configuration',{revision:config.revision,locked:false},master.token);
  const workspace = await get('/api/admin/customization',master.token);
  const original = workspace.selectedTheme;
  assert.ok((await get('/api/admin/customization/presets',master.token)).length > 0);
  assert.equal((await get('/api/admin/customization/themes',master.token)).length,1);
  const draft = await get(`/api/admin/customization/themes/${original._id}`,master.token);
  const configDraft = {...draft.draftConfig,branding:{...draft.draftConfig.branding,websiteName:'Discard this title'}};
  const changed = await call('PUT',`/api/admin/customization/themes/${original._id}/draft`,{config:configDraft,expectedUpdatedAt:draft.updatedAt},master.token);
  const discarded = await call('POST',`/api/admin/customization/themes/${original._id}/discard`,{expectedUpdatedAt:changed.updatedAt},master.token);
  assert.notEqual(discarded.draftConfig.branding.websiteName,'Discard this title');
  await call('POST',`/api/admin/customization/themes/${original._id}/activate`,{expectedUpdatedAt:discarded.updatedAt},master.token);
  assert.equal((await get('/api/website-config')).config.branding.websiteName,original.publishedConfig.branding.websiteName);
});

test('legacy payment aliases create and verify the same signed persisted gateway order', async (t) => {
  const keys=['RAZORPAY_KEY_ID','RAZORPAY_KEY_SECRET','RAZORPAY_MOCK'];
  const previous=Object.fromEntries(keys.map(key=>[key,process.env[key]]));
  t.after(()=>keys.forEach(key=>{if(previous[key]===undefined)delete process.env[key];else process.env[key]=previous[key];}));
  Object.assign(process.env,{RAZORPAY_KEY_ID:'rzp_test_workflow_fixture',RAZORPAY_KEY_SECRET:'workflow-fixture-signing-secret',RAZORPAY_MOCK:'1'});
  await setSettings({razorpayEnabled:true});
  const customer=await createCustomer(),product=await createProduct({stock:3});
  const payment=await call('POST','/api/create-order',{orderItems:[{product:String(product._id),quantity:1,size:'M',color:'Red'}],shippingAddress:validAddress(),paymentMethod:'UPI'},customer.token);
  const paymentId='pay_workflow_fixture';
  const payload={razorpay_order_id:payment.razorpayOrderId,razorpay_payment_id:paymentId,razorpay_signature:require('node:crypto').createHmac('sha256',process.env.RAZORPAY_KEY_SECRET).update(`${payment.razorpayOrderId}|${paymentId}`).digest('hex')};
  await call('POST','/api/verify-payment',payload,customer.token);
  await call('POST','/api/verify-payment',payload,customer.token);
  assert.equal((await get(`/api/orders/${payment.orderId}`,customer.token)).paymentStatus,'Paid');
  assert.equal((await Product.findById(product._id)).stock,2);
});
