const router = require('express').Router();
const { protect } = require('../middleware/authMiddleware');
const { masterOnly } = require('../config/masterOwner');
const controller = require('../controllers/masterController');
router.use(protect, masterOnly);
router.get('/', controller.workspace);
router.get('/clients', controller.clientControl);
router.get('/installations/:id/operations', controller.installationOperations);
router.post('/projects/preview', controller.previewProject);
router.post('/projects/generate', controller.generateProject);
router.patch('/installations/:id', controller.updateInstallation);
router.post('/installations/:id/rotate-key', controller.rotateInstallationKey);
router.post('/installations/:id/deploy', controller.deployInstallation);
router.post('/releases', controller.createRelease);
router.put('/configuration', controller.update);
router.post('/store/setup', controller.update);
router.post('/store/convert', controller.update);
router.get('/export', controller.export);
router.post('/import', controller.import);
router.post('/presets', controller.createPreset);
router.post('/clone', controller.createPreset);
router.patch('/presets/:id', controller.updatePreset);
router.post('/presets/:id/duplicate', controller.duplicatePreset);
router.get('/stores/:id/industry-impact', controller.previewStoreIndustry);
router.patch('/stores/:id/platform', controller.updateStorePlatform);
router.delete('/presets/:id', controller.deletePreset);
router.post('/client-admins', controller.provisionAdmin);
module.exports = router;
