const router = require('express').Router();
const order = require('../controllers/orderController');
const { protect } = require('../middleware/authMiddleware');
const { adminOnly } = require('../middleware/adminMiddleware');
const delivery = require('../controllers/deliveryController');
router.get('/:id/delivery', protect, delivery.details);
router.get('/:id/delivery/label', protect, adminOnly, delivery.label);
router.post('/:id/delivery/:action', protect, adminOnly, delivery.action);
router.post('/', protect, order.createOrder);
router.post('/cod', protect, order.createCodOrder);
router.post('/quote', protect, order.quoteOrder);
router.get('/', protect, adminOnly, order.adminOrders);
router.get('/workspace-summary', protect, adminOnly, order.orderWorkspaceSummary);
router.get('/:id/receipt', protect, order.receipt);
router.put('/:id/status', protect, adminOnly, order.updateOrderStatus);
router.put('/:id/payment-status', protect, adminOnly, order.updatePaymentStatus);
router.patch('/:id/staff-notes', protect, adminOnly, order.addStaffNote);
router.put('/:id/shipping-address', protect, adminOnly, order.updateShippingAddress);
router.put('/:id/shipment', protect, adminOnly, order.updateShipment);
router.delete('/:id', protect, adminOnly, order.deleteOrder);
router.post('/:id/cancel', protect, order.cancelOrder);
router.get('/my-orders', protect, order.myOrders);
router.get('/admin/all', protect, adminOnly, order.adminOrders);
router.get('/admin/workspace-summary', protect, adminOnly, order.orderWorkspaceSummary);
router.get('/admin/:id', protect, adminOnly, order.getOrder);
router.get('/admin/:id/receipt', protect, adminOnly, order.receipt);
router.put('/admin/:id/status', protect, adminOnly, order.updateOrderStatus);
router.put('/admin/:id/payment-status', protect, adminOnly, order.updatePaymentStatus);
router.get('/:id', protect, order.getOrder);
module.exports = router;
