const router = require('express').Router();
const returns = require('../controllers/returnController');
const { protect } = require('../middleware/authMiddleware');
const { adminOnly, requirePermission } = require('../middleware/adminMiddleware');
router.post('/', protect, returns.createReturn);
router.get('/', protect, adminOnly, requirePermission('manage_support'), returns.adminReturns);
router.get('/my-requests', protect, returns.myReturns);
router.get('/admin/all', protect, adminOnly, requirePermission('manage_support'), returns.adminReturns);
router.put('/admin/:id/status', protect, adminOnly, requirePermission('manage_support'), returns.updateReturnStatus);
router.put('/:id/status', protect, adminOnly, requirePermission('manage_support'), returns.updateReturnStatus);
module.exports = router;
