const router = require('express').Router();
const returns = require('../controllers/returnController');
const { protect } = require('../middleware/authMiddleware');
const { adminOnly } = require('../middleware/adminMiddleware');
const delivery = require('../controllers/deliveryController');
const reverse = (req, res, next) => { req.deliveryReturn = true; next(); };
router.get('/:id/delivery', protect, reverse, delivery.details);
router.get('/:id/delivery/label', protect, adminOnly, reverse, delivery.label);
router.post('/:id/delivery/:action', protect, adminOnly, reverse, delivery.action);
router.post('/', protect, returns.createReturn);
router.get('/', protect, adminOnly, returns.adminReturns);
router.get('/my-requests', protect, returns.myReturns);
router.get('/order/:orderId', protect, returns.orderReturns);
router.get('/admin/all', protect, adminOnly, returns.adminReturns);
router.put('/admin/:id/status', protect, adminOnly, returns.updateReturnStatus);
router.put('/:id/status', protect, adminOnly, returns.updateReturnStatus);
module.exports = router;
