const router = require('express').Router();
const review = require('../controllers/reviewController');
const { protect } = require('../middleware/authMiddleware');
const { adminOnly, requirePermission } = require('../middleware/adminMiddleware');
router.get('/', protect, adminOnly, requirePermission('manage_support'), review.adminReviews);
router.get('/admin/all', protect, adminOnly, requirePermission('manage_support'), review.adminReviews);
router.patch('/admin/:id/visibility', protect, adminOnly, requirePermission('manage_support'), review.toggleVisibility);
router.delete('/admin/:id', protect, adminOnly, requirePermission('manage_support'), review.deleteReview);
router.patch('/:id/visibility', protect, adminOnly, requirePermission('manage_support'), review.toggleVisibility);
router.delete('/:id', protect, adminOnly, requirePermission('manage_support'), review.deleteReview);
router.post('/:productId', protect, review.createReview);
router.put('/:productId', protect, review.updateReview);
router.delete('/:productId/mine', protect, review.deleteOwnReview);
router.get('/:productId', review.getReviews);
module.exports = router;
