const mongoose = require('mongoose');

const settingsSchema = new mongoose.Schema({
  storeName: { type: String, default: 'Samira Collection' },
  contactEmail: String,
  contactPhone: String,
  whatsappNumber: String,
  address: String,
  freeShippingMinAmount: { type: Number, default: 999 },
  deliveryCharge: { type: Number, default: 99 },
  codEnabled: { type: Boolean, default: true },
  codCharge: { type: Number, default: 0 },
  codMaxAmount: Number,
  razorpayEnabled: { type: Boolean, default: false },
  upiEnabled: { type: Boolean, default: true },
  cardPaymentEnabled: { type: Boolean, default: true },
  netBankingEnabled: { type: Boolean, default: true },
  walletEnabled: { type: Boolean, default: true },
  socialLinks: Object,
  footerText: String,
  returnPolicy: String,
  privacyPolicy: String,
  termsConditions: String,
  shippingPolicy: String,
  cancellationPolicy: String,
  sizeGuide: String,
  faqs: String,
  ourStory: String,
  legalBusinessName: String,
  gstin: String,
  invoicePrefix: { type: String, default: 'SC' },
  billingAddress: String,
  returnWindowDays: { type: Number, default: 7 },
  appLinks: Object,
  storeId: { type: mongoose.Schema.Types.ObjectId, ref: 'Store', index: true },
  codMinAmount: { type: Number, default: 0 },
  codPincodes: { type: [String], default: [] },
  prepaidDiscountType: { type: String, enum: ['Percentage', 'Flat', ''], default: '' },
  prepaidDiscountValue: { type: Number, default: 0 },
  codConfirmationRequired: { type: Boolean, default: false },
  rtoBlockEnabled: { type: Boolean, default: false },
  rtoBlockMinOrders: { type: Number, default: 0 },
  rtoBlockThreshold: { type: Number, default: 0 },
}, { timestamps: true });

module.exports = mongoose.model('Settings', settingsSchema);
